[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day1"

[[bin]]
name = "day2"

[[bin]]
name = "day3"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
rayon = "1.8.0"
